(defun tasks-new-huid ()
  (format-time-string "%Y%m%d-%H%M%S"))

(defun traverse-from-current-driectory ()
  (let ((dir default-directory))
    (while dir
      (message "%s" dir)
      (setq dir (file-name-parent-directory dir)))))

(defun tasks-find-database0 ()
  (let ((dir default-directory)
        (result nil))
    (while (and dir (not result))
      (let ((task-dir (file-name-concat dir "task")))
        (if (file-directory-p task-dir)
            (setq result task-dir)
          (setq dir (file-name-parent-directory dir)))
        )
      ) result
    )
  )

(defun tasks-find-database ()
  (let ((dir default-directory))
    (catch 'result
      (while dir
        (let ((db-dir (file-name-concat dir "tasks")))
          (if (file-directory-p db-dir)
              (throw 'result db-dir)
            (setq dir (file-name-parent-directory dir))))))))


(defun tasks-create-from-todo0 ()
  (let ((line (thing-at-point 'line)))
    (when (string-match "\\(.*\\)TODO:\\(.*\\)" line)
      (message "PREFIX: %s" (match-string 1 line))
      (message "SUFFIX: %s" (match-string 2 line))))
  )

(defun tasks-create-from-todo1 ()
  (interactive)
  (let ((line (thing-at-point 'line)))
    (when (string-match "\\(.*\\)TODO:\\(.*\\)" line)
      (let ((prefix (match-string 1 line))
            (suffix (match-string 2 line)))
        (delete-line)
        (insert (format "%s TASK(%s):%s\n" prefix (tasks-new-huid) suffix)))
      )
    )
  )

(defun tasks-create-from-todo ()
  (interactive)
  (let ((line (thing-at-point 'line)))
    (when (string-match "\\(.*\\)TODO:\\(.*\\)" line)
      (let ((prefix (string-trim (match-string 1 line)))
            (suffix (match-string 2 line)))
        (message "found TODO: %s" suffix)
        (let ((db-dir (tasks-find-database)))
          (message "found db-dir: %s" db-dir)
          (when db-dir
            (let* ((huid (tasks-new-huid))
                   (task-path (file-name-concat db-dir huid)))
              (if (file-exists-p task-path)
                  (message "ERROR: %s already exists. Trying again later." task-path)
                (mkdir task-path)
                (let ((task-string (format "# %s\n" suffix))
                      (task-md-path (file-name-concat task-path "TASK.md")))
                  (write-region task-string nil task-md-path)
                  (delete-line)
                  (insert (format "%sTask(%s):%s\n" prefix huid suffix))
                  (find-file-other-window task-md-path))
                ))))))
      )
  )
